ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -12,7 +12,6 @@ env:
   CONTAINER_PORT: 8080
   IMAGE_TAG: ${{ github.sha }}  # Use GitHub SHA as the tag for the image
   EKS_CLUSTER_NAME: my-eks-cluster  # EKS cluster name as an environment variable
-  ECR_REPOSITORY_URL: 761018885188.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.SPRING_BOOT_APP_NAME }}  # ECR repository URL
 
 jobs:
   build:
@@ -77,11 +76,15 @@ jobs:
       - name: Create ECR repository if not exists
         run: |
           REPO_NAME="${{ secrets.SPRING_BOOT_APP_NAME }}"
+          if [ -z "$REPO_NAME" ]; then
+            echo "Error: ECR repository name (SPRING_BOOT_APP_NAME) is not set!"
+            exit 1
+          fi
           # Check if the repository exists
-          REPO_EXISTS=$(aws ecr describe-repositories --repository-names $REPO_NAME --region ${{ secrets.AWS_REGION }} --query 'repositories[0].repositoryName' --output text)
+          REPO_EXISTS=$(aws ecr describe-repositories --repository-names "$REPO_NAME" --region ${{ secrets.AWS_REGION }} --query 'repositories[0].repositoryName' --output text)
           if [ "$REPO_EXISTS" == "None" ]; then
             echo "ECR repository does not exist. Creating a new one..."
-            aws ecr create-repository --repository-name $REPO_NAME --region ${{ secrets.AWS_REGION }}
+            aws ecr create-repository --repository-name "$REPO_NAME" --region ${{ secrets.AWS_REGION }}
           else
             echo "ECR repository $REPO_NAME already exists."
           fi
